### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-NoeliaGlez#2]
![Infografia Gestion de proyectos-Noelia González](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-NoeliaGlez/assets/99633910/2527446b-10a8-4bde-bea0-5de6fa89f967)

**Comment by Aricel117** [comment]
Calif: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
